[project]
name = "assignment_bp_roma_cherniak_2026"
version = "0.1.0"
description = "make my own ASL clasifier on A , B , C , D , nothing latters using Pytorch and OpenCV"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "opencv-python>=4.13.0.92",
    "pillow>=12.2.0",
    "torch>=2.11.0",
    "torchvision>=0.26.0",
]

[build_system]
requires = ["hatchling"]
build-backend = "hatchling.build"
